# Uncomment if you want full SQL logs
#spring:
#    jpa:
#        properties:
#            hibernate:
#                show_sql: true
#                format_sql: true
#logging:
#    level:
#        org:
#            hibernate:
#                type: trace
